### ISSUE TITLE
Waiting for elasticsearch to start...

### ISSUE THREAD

**Issue by Sundin** [pastakhov/compose-mediawiki-ubuntu#16]
Hi! Trying to run `docker-compose up`, but it seems to stop at this step:

`web_1            | Waiting for elasticsearch to start...`

Just repeating the same output over and over again, even though the elasticsearch container seems to be running already. Any ideas?

**Comment by ericrector** [comment]
I just built the MediaWiki. It worked like a charm.  The only problem I had (it was on my side) was with git converting the line ending to windows.  I fixed GIT so it would not convert the line endings, rechecked out everything and bam! It worked.

Thank you Pastakhov for your efforts.

Appended: I got it running on 2 other machines.  Hint: let the script run. It might take a while.
