### ISSUE TITLE
Several bugs I have found deploying this

### ISSUE THREAD

**Issue by Hisma** [pastakhov/compose-mediawiki-ubuntu#5]
There is a major bug that happens every time that causes the "web" container to fail with an "exit code 1" error.  I have narrowed down the issue in the "run-apache.sh" file.  the "run maintenance scripts" in the script section causes the exit code to occur.  I don't know why it happens, and the only way I found to by-pass this is to set "auto-update" to "false" in the if statement.  This skips the maintenance scripts section, and then the rest works fine.

the cirrus search does not work.  It gives a general error stating that the search failed.  This is probably related to the fact I had to skip the maintenance script section to get this container to work, as I see there is some maintenance script section related to cirrus search.  I went into "DockerSettings.php" and commented out the cirrus search section.  The wiki works fine with the default search.  

Another major bug is that the "echo" script is broken and causes sql db errors on the wiki.  If you go to the echo extension installation instructions, https://www.mediawiki.org/wiki/Extension:Echo, it says that in addition to adding the extension, you must also import "echo.sql" into your database.  I used the command "mysql -u root -p my_wiki < echo.sql"  to import into my local wiki db from inside the database container.  That fixed the error.

I would also like if there was easier method of having the ability to import existing wiki database into this set-up.  I did it manually, but mounting storage and importing a sql backup of my wiki, and it worked.   I had to tweak the "docker-compose.yml" file to add my local storage volumes to access files on my local server to move files around.  Would be useful to include instructions for users to mount their own storage volumes to certain containers so they can copy files in/out of containers easier.

Last, if you could please add math and mathoid using the restbase framework?  I have tried to add these myself and it is very difficult, since your containers are heavily scripted and rely so much on different environment variables.  You already have restbase and parsoid, so adding mathoid shouldn't be too hard. 

Thank you for your hard work.  After getting around the bugs (which may be my fault, not sure) and modifying tweaking the files, I got everything working, and it's a great set-up.  More than what I need for my own private wiki, but still extremely fast and I love that you got visual editor working with restbase.

**Comment by Hisma** [comment]
By the way, I think the error is that the LocalSettings.php file gets created incorrectly.  The update script needs to connect to the mediawiki sql database.  But I noticed that when analyzing LocalSettings.php, 
"$wgDBpassword =" was blank, even though I specified a db password in the docker-compose.yml file.  It fails to connect to the db and I think that breaks the script.  I don't know if it's something I did somehow, but I am 100% sure I did not leave that pw blank in my composer config.  Also, the fact that the password was blank also breaks access to the wiki.  Once I put my correct pw in it fixed it.

Might want to test and see if it happens to you and can fix it.

**Comment by pastakhov** [comment]
Hi,
Sorry for the late reply, I was not available.

About bugs... It would be helpful to see all logs with errors.
And I tested all before pushing patches, it all works fine for me. There may be a problem with the versions of the docker, I use the latest versions and did not set myself the task of compatibility with older versions.

> I would also like if there was easier method of having the ability to import existing wiki database

Yes, I'll write such instruction.

> Last, if you could please add math and mathoid using the restbase framework? 

yes, it will be added.

Thanks for the feedback.

**Comment by Hisma** [comment]
hmm, I will have to rebuild the image again to get the logs.  not sure I want to do that just yet now that I got it all up and running the way I want (I managed to get math & mathoid working by hacking your scripts).  
But I don't see anywhere in your build scripts that you add the "echo.sql" to your database.  Without it, echo extension will not work properly and will break your wiki if enabled.  It's part of the extension installation instructions.

I am using Docker version 17.06.1-ce, build 874a737 on ubuntu 16.04, which is very recent.  Have you tried changing the default auto-generated DB password and see if it still builds correctly?  Again, my issue was that "$wgDBpassword" was blank in my LocalSettings.php, despite including a db password in the composer script.  It fails with exit code 1, specifically because when it runs the maintenance update scripts it must be able to connect to the database.  My guess is your script accidentally misses to populate this parameter during the build process.  If you leave your db password blank in the build script then this issue would probably not come up.

Sorry wish I could be more help... I just don't want to rebuild my docker image to get error logs since I customized it to work exactly the way I want.  I would just look into the issues I stated... if you are able to build all your containers from a blank slate with a custom db password, and you don't get any exit errors and everything works, then I will have to assume the problem was something on my end.  

Then if you could just add math and mathoid, you'd have a very complete package for most people.  I would suggest some other extensions I use, like MsUpload (allows drag and drop to upload files), MsCatSelect (allows to easily add and manage categories), and JSBreadCrumbs (obvious... add breadcrumbs), then I would literally not have to change anything.  But I don't want to add too much bloat to your already fairly extensive extensions.  

You are awesome to do all this work and take time to listen to my suggestions :).  Thanks!

**Comment by pastakhov** [comment]
> But I don't see anywhere in your build scripts that you add the "echo.sql" to your database.

Looks like a stupid solution, it must be processed by update.php maintenance script. I'll try to fix it extension code, have no idea why it is not done.

I'm going to move web to separate container as all other already done. Also I want to write generator of LocalSetting.php file, it should work better and be easier for debugging. And of course add math & mathoid and more. And since web will be separate container it should be easy to modify one and add as much additional extensions as you need :)

**Comment by pastakhov** [comment]
Seems Echo works fine without load echo.sql to database. Maybe it was fixed.

**Comment by Hisma** [comment]
okay, thanks for all the info!  I'll close this one out for you, sounds like you're on top of it.
